apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-discovery
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.controller.componentName}}
  ports:
    - protocol: TCP
      port: {{.Values.controller.agentListenerPort}}
      targetPort: {{.Values.controller.agentListenerPort}}
