kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{.Values.persistence.claimName}}
  namespace:  {{.Values.namespace}}
spec:
  accessModes:
    - {{.Values.persistence.accessMode}}
  resources:
    requests:
      storage: {{.Values.persistence.size}}